//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: data-contract serialization ([DataContract]/[DataMember]) enabled
    
// Generated from: NetMessage.proto
namespace ProtoMessage
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerInfo")]
  [global::System.Runtime.Serialization.DataContract(Name=@"PlayerInfo")]
  public partial class PlayerInfo : global::ProtoBuf.IExtensible
  {
    public PlayerInfo() {}
    
    private int _seatID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"seatID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.Runtime.Serialization.DataMember(Name=@"seatID", Order = 1, IsRequired = true)]
    
    public int seatID
    {
      get { return _seatID; }
      set { _seatID = value; }
    }
    private string _playerName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"playerName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.Runtime.Serialization.DataMember(Name=@"playerName", Order = 2, IsRequired = true)]
    
    public string playerName
    {
      get { return _playerName; }
      set { _playerName = value; }
    }
    private bool _isReady;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"isReady", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.Runtime.Serialization.DataMember(Name=@"isReady", Order = 3, IsRequired = true)]
    
    public bool isReady
    {
      get { return _isReady; }
      set { _isReady = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoMessage.CardInfo> _cardsList = new global::System.Collections.Generic.List<ProtoMessage.CardInfo>();
    [global::ProtoBuf.ProtoMember(4, Name=@"cardsList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.Runtime.Serialization.DataMember(Name=@"cardsList", Order = 4, IsRequired = false)]
    
    public global::System.Collections.Generic.List<ProtoMessage.CardInfo> cardsList
    {
      get { return _cardsList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CardInfo")]
  [global::System.Runtime.Serialization.DataContract(Name=@"CardInfo")]
  public partial class CardInfo : global::ProtoBuf.IExtensible
  {
    public CardInfo() {}
    
    private int _index;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.Runtime.Serialization.DataMember(Name=@"index", Order = 1, IsRequired = true)]
    
    public int index
    {
      get { return _index; }
      set { _index = value; }
    }
    private int _cardType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"cardType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.Runtime.Serialization.DataMember(Name=@"cardType", Order = 2, IsRequired = true)]
    
    public int cardType
    {
      get { return _cardType; }
      set { _cardType = value; }
    }
    private int _level;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.Runtime.Serialization.DataMember(Name=@"level", Order = 3, IsRequired = true)]
    
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private int _hp;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"hp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.Runtime.Serialization.DataMember(Name=@"hp", Order = 4, IsRequired = true)]
    
    public int hp
    {
      get { return _hp; }
      set { _hp = value; }
    }
    private int _atk;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"atk", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.Runtime.Serialization.DataMember(Name=@"atk", Order = 5, IsRequired = true)]
    
    public int atk
    {
      get { return _atk; }
      set { _atk = value; }
    }
    private int _positionX;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"positionX", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.Runtime.Serialization.DataMember(Name=@"positionX", Order = 6, IsRequired = true)]
    
    public int positionX
    {
      get { return _positionX; }
      set { _positionX = value; }
    }
    private int _positionY;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"positionY", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.Runtime.Serialization.DataMember(Name=@"positionY", Order = 7, IsRequired = true)]
    
    public int positionY
    {
      get { return _positionY; }
      set { _positionY = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NetMessage")]
  [global::System.Runtime.Serialization.DataContract(Name=@"NetMessage")]
  public partial class NetMessage : global::ProtoBuf.IExtensible
  {
    public NetMessage() {}
    
    private ProtoMessage.NetMessageRequest _Request;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Request", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.Runtime.Serialization.DataMember(Name=@"Request", Order = 1, IsRequired = true)]
    
    public ProtoMessage.NetMessageRequest Request
    {
      get { return _Request; }
      set { _Request = value; }
    }
    private ProtoMessage.NetMessageResponse _Response;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Response", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.Runtime.Serialization.DataMember(Name=@"Response", Order = 2, IsRequired = true)]
    
    public ProtoMessage.NetMessageResponse Response
    {
      get { return _Response; }
      set { _Response = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NetMessageRequest")]
  [global::System.Runtime.Serialization.DataContract(Name=@"NetMessageRequest")]
  public partial class NetMessageRequest : global::ProtoBuf.IExtensible
  {
    public NetMessageRequest() {}
    
    private ProtoMessage.PlayerJoinRoomRequest _playerJoinRoom;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerJoinRoom", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.Runtime.Serialization.DataMember(Name=@"playerJoinRoom", Order = 1, IsRequired = true)]
    
    public ProtoMessage.PlayerJoinRoomRequest playerJoinRoom
    {
      get { return _playerJoinRoom; }
      set { _playerJoinRoom = value; }
    }
    private ProtoMessage.ChangeReadyRequest _changeReady;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"changeReady", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.Runtime.Serialization.DataMember(Name=@"changeReady", Order = 2, IsRequired = true)]
    
    public ProtoMessage.ChangeReadyRequest changeReady
    {
      get { return _changeReady; }
      set { _changeReady = value; }
    }
    private ProtoMessage.PlayerJoinGameRequest _playerJoinGame;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"playerJoinGame", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.Runtime.Serialization.DataMember(Name=@"playerJoinGame", Order = 3, IsRequired = true)]
    
    public ProtoMessage.PlayerJoinGameRequest playerJoinGame
    {
      get { return _playerJoinGame; }
      set { _playerJoinGame = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NetMessageResponse")]
  [global::System.Runtime.Serialization.DataContract(Name=@"NetMessageResponse")]
  public partial class NetMessageResponse : global::ProtoBuf.IExtensible
  {
    public NetMessageResponse() {}
    
    private ProtoMessage.PlayerJoinRoomResponse _PlayerJoinRoom;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"PlayerJoinRoom", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.Runtime.Serialization.DataMember(Name=@"PlayerJoinRoom", Order = 1, IsRequired = true)]
    
    public ProtoMessage.PlayerJoinRoomResponse PlayerJoinRoom
    {
      get { return _PlayerJoinRoom; }
      set { _PlayerJoinRoom = value; }
    }
    private ProtoMessage.AddPlayerToRoomResponse _AddPlayerToRoom;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"AddPlayerToRoom", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.Runtime.Serialization.DataMember(Name=@"AddPlayerToRoom", Order = 2, IsRequired = true)]
    
    public ProtoMessage.AddPlayerToRoomResponse AddPlayerToRoom
    {
      get { return _AddPlayerToRoom; }
      set { _AddPlayerToRoom = value; }
    }
    private ProtoMessage.ChangeReadyResponse _changeReady;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"changeReady", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.Runtime.Serialization.DataMember(Name=@"changeReady", Order = 3, IsRequired = true)]
    
    public ProtoMessage.ChangeReadyResponse changeReady
    {
      get { return _changeReady; }
      set { _changeReady = value; }
    }
    private ProtoMessage.LeaveRoomResponse _leaveRoom;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"leaveRoom", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.Runtime.Serialization.DataMember(Name=@"leaveRoom", Order = 4, IsRequired = true)]
    
    public ProtoMessage.LeaveRoomResponse leaveRoom
    {
      get { return _leaveRoom; }
      set { _leaveRoom = value; }
    }
    private ProtoMessage.ReadyToStartResponse _readyToStart;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"readyToStart", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.Runtime.Serialization.DataMember(Name=@"readyToStart", Order = 5, IsRequired = true)]
    
    public ProtoMessage.ReadyToStartResponse readyToStart
    {
      get { return _readyToStart; }
      set { _readyToStart = value; }
    }
    private ProtoMessage.FailedToJoinGameResponse _failedToJoinGame;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"failedToJoinGame", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.Runtime.Serialization.DataMember(Name=@"failedToJoinGame", Order = 6, IsRequired = true)]
    
    public ProtoMessage.FailedToJoinGameResponse failedToJoinGame
    {
      get { return _failedToJoinGame; }
      set { _failedToJoinGame = value; }
    }
    private ProtoMessage.GameStartResponse _gameStart;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"gameStart", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.Runtime.Serialization.DataMember(Name=@"gameStart", Order = 7, IsRequired = true)]
    
    public ProtoMessage.GameStartResponse gameStart
    {
      get { return _gameStart; }
      set { _gameStart = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerJoinRoomRequest")]
  [global::System.Runtime.Serialization.DataContract(Name=@"PlayerJoinRoomRequest")]
  public partial class PlayerJoinRoomRequest : global::ProtoBuf.IExtensible
  {
    public PlayerJoinRoomRequest() {}
    
    private string _playerName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.Runtime.Serialization.DataMember(Name=@"playerName", Order = 1, IsRequired = true)]
    
    public string playerName
    {
      get { return _playerName; }
      set { _playerName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerJoinRoomResponse")]
  [global::System.Runtime.Serialization.DataContract(Name=@"PlayerJoinRoomResponse")]
  public partial class PlayerJoinRoomResponse : global::ProtoBuf.IExtensible
  {
    public PlayerJoinRoomResponse() {}
    
    private bool _successJoin;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"successJoin", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.Runtime.Serialization.DataMember(Name=@"successJoin", Order = 1, IsRequired = true)]
    
    public bool successJoin
    {
      get { return _successJoin; }
      set { _successJoin = value; }
    }
    private string _reason;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"reason", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.Runtime.Serialization.DataMember(Name=@"reason", Order = 2, IsRequired = true)]
    
    public string reason
    {
      get { return _reason; }
      set { _reason = value; }
    }
    private int _selfSeatID;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"selfSeatID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.Runtime.Serialization.DataMember(Name=@"selfSeatID", Order = 3, IsRequired = true)]
    
    public int selfSeatID
    {
      get { return _selfSeatID; }
      set { _selfSeatID = value; }
    }
    private ulong _selfNetID;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"selfNetID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.Runtime.Serialization.DataMember(Name=@"selfNetID", Order = 4, IsRequired = true)]
    
    public ulong selfNetID
    {
      get { return _selfNetID; }
      set { _selfNetID = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoMessage.PlayerInfo> _allPlayers = new global::System.Collections.Generic.List<ProtoMessage.PlayerInfo>();
    [global::ProtoBuf.ProtoMember(5, Name=@"allPlayers", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.Runtime.Serialization.DataMember(Name=@"allPlayers", Order = 5, IsRequired = false)]
    
    public global::System.Collections.Generic.List<ProtoMessage.PlayerInfo> allPlayers
    {
      get { return _allPlayers; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AddPlayerToRoomResponse")]
  [global::System.Runtime.Serialization.DataContract(Name=@"AddPlayerToRoomResponse")]
  public partial class AddPlayerToRoomResponse : global::ProtoBuf.IExtensible
  {
    public AddPlayerToRoomResponse() {}
    
    private ProtoMessage.PlayerInfo _player;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"player", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.Runtime.Serialization.DataMember(Name=@"player", Order = 1, IsRequired = true)]
    
    public ProtoMessage.PlayerInfo player
    {
      get { return _player; }
      set { _player = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChangeReadyRequest")]
  [global::System.Runtime.Serialization.DataContract(Name=@"ChangeReadyRequest")]
  public partial class ChangeReadyRequest : global::ProtoBuf.IExtensible
  {
    public ChangeReadyRequest() {}
    
    private bool _readyState;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"readyState", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.Runtime.Serialization.DataMember(Name=@"readyState", Order = 1, IsRequired = true)]
    
    public bool readyState
    {
      get { return _readyState; }
      set { _readyState = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChangeReadyResponse")]
  [global::System.Runtime.Serialization.DataContract(Name=@"ChangeReadyResponse")]
  public partial class ChangeReadyResponse : global::ProtoBuf.IExtensible
  {
    public ChangeReadyResponse() {}
    
    private int _seatID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"seatID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.Runtime.Serialization.DataMember(Name=@"seatID", Order = 1, IsRequired = true)]
    
    public int seatID
    {
      get { return _seatID; }
      set { _seatID = value; }
    }
    private bool _readyState;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"readyState", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.Runtime.Serialization.DataMember(Name=@"readyState", Order = 2, IsRequired = true)]
    
    public bool readyState
    {
      get { return _readyState; }
      set { _readyState = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LeaveRoomResponse")]
  [global::System.Runtime.Serialization.DataContract(Name=@"LeaveRoomResponse")]
  public partial class LeaveRoomResponse : global::ProtoBuf.IExtensible
  {
    public LeaveRoomResponse() {}
    
    private int _triggerSeatID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"triggerSeatID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.Runtime.Serialization.DataMember(Name=@"triggerSeatID", Order = 1, IsRequired = true)]
    
    public int triggerSeatID
    {
      get { return _triggerSeatID; }
      set { _triggerSeatID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReadyToStartResponse")]
  [global::System.Runtime.Serialization.DataContract(Name=@"ReadyToStartResponse")]
  public partial class ReadyToStartResponse : global::ProtoBuf.IExtensible
  {
    public ReadyToStartResponse() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerJoinGameRequest")]
  [global::System.Runtime.Serialization.DataContract(Name=@"PlayerJoinGameRequest")]
  public partial class PlayerJoinGameRequest : global::ProtoBuf.IExtensible
  {
    public PlayerJoinGameRequest() {}
    
    private ProtoMessage.PlayerInfo _player;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"player", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.Runtime.Serialization.DataMember(Name=@"player", Order = 1, IsRequired = true)]
    
    public ProtoMessage.PlayerInfo player
    {
      get { return _player; }
      set { _player = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FailedToJoinGameResponse")]
  [global::System.Runtime.Serialization.DataContract(Name=@"FailedToJoinGameResponse")]
  public partial class FailedToJoinGameResponse : global::ProtoBuf.IExtensible
  {
    public FailedToJoinGameResponse() {}
    
    private int _seatID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"seatID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.Runtime.Serialization.DataMember(Name=@"seatID", Order = 1, IsRequired = true)]
    
    public int seatID
    {
      get { return _seatID; }
      set { _seatID = value; }
    }
    private string _errorReason;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"errorReason", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.Runtime.Serialization.DataMember(Name=@"errorReason", Order = 2, IsRequired = true)]
    
    public string errorReason
    {
      get { return _errorReason; }
      set { _errorReason = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GameStartResponse")]
  [global::System.Runtime.Serialization.DataContract(Name=@"GameStartResponse")]
  public partial class GameStartResponse : global::ProtoBuf.IExtensible
  {
    public GameStartResponse() {}
    
    private readonly global::System.Collections.Generic.List<ProtoMessage.PlayerInfo> _playersList = new global::System.Collections.Generic.List<ProtoMessage.PlayerInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"playersList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.Runtime.Serialization.DataMember(Name=@"playersList", Order = 1, IsRequired = false)]
    
    public global::System.Collections.Generic.List<ProtoMessage.PlayerInfo> playersList
    {
      get { return _playersList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}